yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.forbidden'
handler500 = 'core.views.internal_server_error'

if settings.DEBUG:
    import debug_toolbar
    
    # urlpatterns += static(
    #     settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    # )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(
        blank=True,
        null=True,
        unique=True,
        verbose_name='/адрес',
    )
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Название группы',
        help_text='Выберите группу',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date', '-id']


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата комментирования',
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-created', '-id']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Кто подписывается',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='На кого подписываются',
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm


DISPLAYED_POSTS = 10


def get_page(request, post_list):
    paginator = Paginator(post_list, DISPLAYED_POSTS)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    post_list = Post.objects.all()
    page_obj = get_page(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = get_page(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            author__following__user=request.user).exists()
    else:
        following = False
    post_list = user.posts.all()
    page_obj = get_page(request, post_list)
    context = {
        'page_obj': page_obj,
        'author': user,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author)
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    context = {
        'is_edit': True,
        'form': form,
    }
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)

    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    user = request.user
    followings = Post.objects.filter(
        author__following__user=user
    )
    page_obj = get_page(request, followings)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(
            user=user,
            author=author,
        )
    return redirect('posts:index')


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author and Follow.objects.filter(
        user=user,
        author=author,
    ).exists():
        Follow.objects.filter(
            user=user,
            author=author,
        ).delete()
    return redirect('posts:index')

yatube/templates/posts/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Новый пост
            {% endif %}            
          </div>
          <div class="card-body">        
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  {{ form.text.label }}
                  <span class="required text-danger" >*</span>                  
                </label>
                {{ form.text }}
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.text.help_text }}
                </small>                  
              </div>            
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  {{ form.group.label }}
                </label>
                {{ form.group }}
                <small id="id_group-help" class="form-text text-muted">
                  {{ form.group.help_text }}
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_image">
                  Картинка
                </label>
                {% if is_edit %}
                {% thumbnail form.image as im %}
                На данный момент:
                
                  <a href="{{ form.instance.image.url }}">
                    {{ form.instance.image.url }}
                  </a>
                {% endthumbnail %}
                {% endif %}
                <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                {% endif %}   
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Подписки{% endblock %}
{% block content %}
{% load cache %}
{% cache 20 follow_index %}
{% include 'posts/includes/switcher.html' %}
<div class="container py-5">
  {% for post in page_obj %}
    <ul>
      <li>
        <a href="{% url 'posts:profile' post.author.username %}">Автор: {{ post.author.get_full_name }} {{ post.author.username }}</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "400x400" crop="center" as im %}
      <img class="card-img my-2" src="{{ post.image.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %} 
    <p>{{ post.text }}</p>
    {% if post.group %}
    <li class="list-group-item">
      Группа {{ post.group }}
    </li>
    <li class="list-group-item">
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    </li>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endcache %}
{% include 'posts/includes/paginator.html' %}
</div>
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p> {{ group.description }} </p>
    {% for post in page_obj %}
      <ul>
        <li>
          <a href="{% url 'posts:profile' post.author.username %}">Автор: {{ post.author.get_full_name }} {{ post.author.username }}</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "400x400" crop="center" as im %}
        <img class="card-img my-2" src="{{ post.image.url }}" width="{{ im.width }}" height="{{ im.height }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
  </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load cache %}
{% cache 20 index_page %}
{% include 'posts/includes/switcher.html' %}
<div class="container py-5">
  {% for post in page_obj %}
    <ul>
      <li>
        <a href="{% url 'posts:profile' post.author.username %}">Автор: {{ post.author.get_full_name }} {{ post.author.username }}</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "400x400" crop="center" as im %}
      <img class="card-img my-2" src="{{ post.image.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %} 
    <p>{{ post.text }}</p>
    {% if post.group %}
    <li class="list-group-item">
      Группа {{ post.group }}
    </li>
    <li class="list-group-item">
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    </li>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endcache %}
{% include 'posts/includes/paginator.html' %}
</div>
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Пост {{ post.text|slice:':30' }}{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа {{ post.group }}
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          </li>
        {% endif %}
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">Автор: {{ post.author.get_full_name }} {{ post.author.username }}</a>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{ post.author.posts.count }}</span >
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "400x400" crop="center" as im %}
        <img class="card-img my-2" src="{{ post.image.url }}" width="{{ im.width }}" height="{{ im.height }}">
      {% endthumbnail %} 
        <p>
          {{ post.text }}
        </p>
          {% if post.author == request.user %}
            <a class="btn btn-primary" href="{% url "posts:post_edit" post.id %}">
              Редактировать запись
            </a>
          {% endif %}
        {% include 'posts/comments.html' %}
    </article>
  </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ author }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    <div class="mb-5">
      {% if following %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
       {% endif %}
    </div>
    {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }} {{ post.author.username }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "400x400" crop="center" as im %}
      <img class="card-img my-2" src="{{ post.image.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %} 
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
      {% if post.group %}
      <li class="list-group-item">
        Группа {{ post.group }}
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      </li>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
  {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}